version: '2'
volumes:
  z2m-data:
  node-data:
services:
    mosquitto:
      build: ./MOSQUITTO
      ports:
        - "8883:8883"
    node:
      build: ./NODE
      volumes:
        - node-data:/data
      ports:
        - "1880:1880"
    zigbee2mqtt:
      build: ./ZIGBEE
      volumes:
        - z2m-data:/app/data
      ports:
        - "8008:8008"
      devices:
        - "/dev/ttyUSB0:/dev/ttyUSB0"
      cap_add:
        - SYS_RAWIO
      privileged: true
    reverse-proxy:
      build: ./NGINX
      ports:
        - "80:80"
      depends_on:
          - mosquitto
          - node
          - zigbee2mqtt
